export const AGREGAR_PRODUCTO = "AGREGAR_PRODUCTO";
export const AGREGAR_PRODUCTO_EXITO = "AGREGAR_PRODUCTO_EXITO";
export const AGREGAR_PRODUCTO_ERROR = "AGREGAR_PRODUCTO_ERROR";

export const OBTENER_PRODUCTOS = "OBTENER_PRODUCTOS";
export const OBTENER_PRODUCTOS_EXITO = "OBTENER_PRODUCTOS_EXITO";
export const OBTENER_PRODUCTOS_ERROR = "OBTENER_PRODUCTOS_ERROR";

export const OBTENER_ELIMINAR = "OBTENER_ELIMINAR";
export const OBTENER_ELIMINAR_EXITO = "OBTENER_ELIMINAR_EXITO";
export const OBTENER_ELIMINAR_ERROR = "OBTENER_ELIMINAR_ERROR";

export const EDITAR = "EDITAR";
export const EDITAR_PRODUCTO = "EDITAR_PRODUCTO";
export const EDITAR_EXITO = "EDITAR_EXITO";
export const EDITAR_ERROR = "EDITAR_ERROR";
